# Generated by Django 5.1.1 on 2024-09-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CL', 'Classic'), ('FR', 'Fringe'), ('CR', 'Carnivore'), ('VA', 'Vegan'), ('VE', 'Vegetarian')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.JSONField(default={}),
        ),
    ]
