# Generated by Django 5.1.1 on 2024-09-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_product_category_product_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="ingredients",
            field=models.JSONField(default=dict),
        ),
    ]
