# Generated by Django 5.1.1 on 2024-09-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_product_ingredients"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField()),
            ],
        ),
    ]
